before_script:
 - sudo apt-get install ant-optional
 - export OPTS="-server -Xmx3072M"
 - export JAVA_OPTS="${JAVA_OPTS} ${OPTS}"
 - export ANT_OPTS="${ANT_OPTS} ${OPTS}"
 - echo $JAVA_OPTS
 - echo $ANT_OPTS

dist: trusty

language: java

jdk:
  - oraclejdk9
  - oraclejdk8
#  - oraclejdk7
#  - oraclejdk6

#  - openjdk9
  - openjdk8
  - openjdk7
# - openjdk6

env:
  - TEST_SUITE=run_tests
#  - TEST_SUITE=mathematics
#  - TEST_SUITE=numbers
#  - TEST_SUITE=search
#  - TEST_SUITE=sequences
#  - TEST_SUITE=strings
#  - TEST_SUITE=data_structures
#  - TEST_SUITE=sorts

script: "ant $TEST_SUITE"
